/*
 * Reicon icons, vendored.
 *
 * Generated by `scripts/build-reicon.mjs` from reicon@1.2.4 — MIT,
 * © REICON. Do not edit by hand; re-run the generator.
 *
 * Outline weight only. Reicon's filled weight is `fill="currentColor"` with no
 * stroke, and `base` sets `fill: none`, so a filled icon renders as nothing at
 * all — indistinguishable from a record nobody gave an icon.
 *
 * The stroke, width, caps and joins are stripped by the generator: `base`
 * supplies all four on the parent `<svg>`, at this set's 1.7 rather than
 * Reicon's 1.5, so a borrowed glyph carries the same weight as a drawn one.
 * Mixed stroke weights in one grid read as sloppy before anybody can say why.
 *
 * 4 icons, chosen as subjects this business would point a record at
 * rather than as a pack. See the generator's own note for what was left behind.
 */
import { base, type P } from "./icon-base";

/** `ram` — reicon `ram`. */
export const IconReRam = (p: P) => (
  <svg {...base} {...p}><path d="M3.5 7V17C3.5 20 4.97 22 8.5 22H15.5C18.97 22 20.5 20 20.5 17V15.83C20.5 15.3 20.29 14.79 19.91 14.42L19.08 13.59C18.7 13.21 18.49 12.71 18.49 12.18V10C18.49 9.45 18.94 9 19.49 9C20.04 9 20.49 8.55 20.49 8V7C20.49 4 18.96 2 15.49 2H8.49C4.97 2 3.5 4 3.5 7Z"/><path d="M7.98998 21.97L7.97998 19C7.97998 17.89 8.86998 17 9.97998 17H13.99C15.09 17 15.98 17.89 15.99 18.99L16.02 21.98"/><path d="M13.97 7.78003H7.96997"/></svg>
);

/** `password` — reicon `password2`. */
export const IconRePassword2 = (p: P) => (
  <svg {...base} {...p}><line x1="20.3333" y1="5" x2="20.3333" y2="19"></line><line x1="3.012" y1="10.9293" x2="5.6667" y2="11.792"></line><line x1="4.0253" y1="14.0493" x2="5.6667" y2="11.792"></line><line x1="7.308" y1="14.0493" x2="5.6667" y2="11.792"></line><line x1="8.3213" y1="10.9293" x2="5.6667" y2="11.792"></line><line x1="5.6667" y1="9" x2="5.6667" y2="11.792"></line><line x1="11.3453" y1="10.9293" x2="14" y2="11.792"></line><line x1="12.3586" y1="14.0493" x2="14" y2="11.792"></line><line x1="15.6413" y1="14.0493" x2="14" y2="11.792"></line><line x1="16.6546" y1="10.9293" x2="14" y2="11.792"></line><line x1="14" y1="9" x2="14" y2="11.792"></line></svg>
);

/** `bluetooth` — reicon `bluetooth3`. */
export const IconReBluetooth3 = (p: P) => (
  <svg {...base} {...p}><path d="M5.63965 18.64L17.9896 7.31998C18.4996 6.84998 18.4896 6.09997 17.9496 5.64997L14.0996 2.43998C13.0996 1.60998 12.2796 1.98998 12.2796 3.28998V20.71C12.2796 22.01 13.0996 22.39 14.0996 21.56L17.9496 18.35C18.4896 17.9 18.4996 17.15 17.9896 16.68L5.63965 5.35996"/></svg>
);

/** `legal` — reicon `courthouse`. */
export const IconReCourthouse = (p: P) => (
  <svg {...base} {...p}><path d="M2 22H22"/><path d="M12 2C13.6 2.64 15.4 2.64 17 2V5C15.4 5.64 13.6 5.64 12 5V2Z"/><path d="M12 5V8"/><path d="M17 8H7C5 8 4 9 4 11V22H20V11C20 9 19 8 17 8Z"/><path d="M4.58008 12H19.4201"/><path d="M7.98999 12V22"/><path d="M11.99 12V22"/><path d="M15.99 12V22"/></svg>
);

/** The keys this file contributes, for `iconMap`. */
export const reiconMap = {
  "ram": IconReRam,
  "password": IconRePassword2,
  "bluetooth": IconReBluetooth3,
  "legal": IconReCourthouse,
} as const;
